import Head from 'next/head'
import { Inter } from 'next/font/google'

import Homes from '../components/home/home'

const inter = Inter({ subsets: ['latin'] })

export default function Home(props) {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Homes data={props.data} />
      </main>
    </>
  )
}

export async function getServerSideProps() {

  const { events_categories } = await import('../data/data.json')

  return {
    props: {
      data: events_categories,
    }
  }
}