import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home(props) {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
          <img src="" alt="sss" />
          <a href="/">Home</a>
          <a href="/event">Events</a>
          <a href="/about">About Us</a>
        </nav>
      </header>

      <main className={styles.name}>
      <h1>{props.title}</h1>
        <a href=""></a>
        <img src="" alt="" />
        <div>
          <h1>Events in London</h1>
          <p> dfgdg dfgd fgd dfgdgd dfgdgdf dfg dg dgdfg gdffgdgdg</p>
        </div>

        <a href=""></a>
        <img src="" alt="" />
        <div>
          <h1>Events in Sanantonio</h1>
          <p> dfgdg dfgd fgd dfgdgd dfgdgdf dfg dg dgdfg gdffgdgdg</p>
        </div>

        <a href=""></a>
        <img src="" alt="" />
        <div>
          <h1>Events in Austin</h1>
          <p> dfgdg dfgd fgd dfgdgd dfgdgdf dfg dg dgdfg gdffgdgdg</p>
        </div>
      </main>
    </>
  )
}

export function getServerSideProps() {
  return {
    props: {
      title: 'hello'
    }
  }
}